docs(dune): Recursively fix the error about a missing public_name, cont'ed
(Error: `Library "_" is private, it cannot be a dependency of a public library.
You need to give "_" a public name.)

Now, the only remaining error raised by `make` is:
```
Error: Multiple rules generated for
_build/install/default/lib/learn-ocaml/test_lib/test_lib.cmi:
- src/grader/test_lib/dune:29
- src/grader/dune:41
-> required by _build/default/learn-ocaml.install
-> required by alias install
         ppx src/grader-plugins/mutation_test.pp.mli
         ppx src/grader-plugins/mutation_test.pp.ml
make: *** [Makefile:13: build] Error
```