chore(Makefile): Add "rm -f docs/odoc.html" step
* so that "make update-fr-translation" shouldn't raise:

  ```
  File "docs/_unknown_", line 1, characters 0-0:
  Error: File unavailable: docs/odoc.html
  make: *** [Makefile:12: build] Error 1
  ```

* but this fix is probably incomplete.