docs(dune): Recursively fix the error about a missing public_name
Error: `Library "_" is private, it cannot be a dependency of a public library.
You need to give "_" a public name.